image:
  repository: iujege/cicd_orbit
  tag: 53c99f0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true

serviceAccount:
  enabled: true

autoscaling:
  enabled: true