image:
  repository: iujege/cicd_orbit
  tag: 801b57b
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

serviceAccount:
  enabled: false

autoscaling:
  enabled: false
