image:
  repository: iujege/cicd_orbit
  tag: cfcae10
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true

serviceAccount:
  enabled: true

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80