name: CICD ORBIT

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Short SHA
        run: |
          echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t iujege/cicd_orbit:${{ env.SHORT_SHA }} .

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push iujege/cicd_orbit:${{env.SHORT_SHA}}

      - name: Configure git author
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "ci@igba.com"

      - name: Update Helm chart with new image tag
        run: |
          sed -i "s/tag: .*/tag: ${{ env.SHORT_SHA }}/" ./cicd-orbit/values.yaml
          git add ./cicd-orbit/values.yaml
          git commit -m "Update image tag to ${{ env.SHORT_SHA }}"
          git push
